### ISSUE TITLE
start_datetime is required argument even with start_datetime in tap_config.json  

### ISSUE THREAD

**Issue by dustymaxa** [anelendata/tap-bigquery#15]
The project documentation is saying : 

`"start_datetime must also be set in the config file or as the command line argument",`

but I have an `"state or start_datetime must be specified"` error even if I have a specified  start_datetime in my tap_config.json  

Thanks,

Dusty

**Comment by daigotanaka** [comment]
Hi Dusty,

Can I see your config? You should mask password or any sensitive info. I just need to see the format you are using.

Also please make sure you are using version v0.3.2 (or later in case I released something after this post).
To update:
```
pip install -U tap-bigquery
```
(Related (closed) issue: https://github.com/anelendata/tap-bigquery/issues/11 )

Daigo

**Comment by dustymaxa** [comment]
HI @daigotanaka ,

Here is my tap_config file and the results of the discovery command. I'm using the v0.3.2.

![image](https://user-images.githubusercontent.com/57405891/97176851-eff9d800-176b-11eb-8c15-aaaed59f86a6.png)


![image](https://user-images.githubusercontent.com/57405891/97176906-fee08a80-176b-11eb-8a99-27a9c5c55fc9.png)

![image](https://user-images.githubusercontent.com/57405891/97176977-1c155900-176c-11eb-9201-bf064e77cfee.png)


Thanks,

Dusty

**Comment by daigotanaka** [comment]
Yes, I confirmed this is a bug. Thanks for reporting.
The workaround is to specify `--start_datetime "2019-09-23T00:00:00Z"` in the command line for both discovery mode and sync mode.
Meanwhile, I'm fixing it now. Sorry for the convenience.
