### ISSUE TITLE
Running tap without datetime_key?

### ISSUE THREAD

**Issue by georgetam** [anelendata/tap-bigquery#21]
Is it possible to use this tap without the datetime_key? I'm trying to sync a table where the date column is sometimes null but I still want to grab all of the rows.

**Comment by daigotanaka** [comment]
@georgetam: I know you just closed it but just to clarify for the later reference, it currently does not work without settings datetime_key. But I see people want to use this to do full-sync for every run. I can consider it as an enhancement request and modifying the code. Just let me know by reopening and commenting.
