### ISSUE TITLE
Support `credentials_json` as option for full-text of `client_secrets.json`

### ISSUE THREAD

**Issue by aaronsteers** [anelendata/tap-bigquery#26]
In some runtimes, it is not feasible to load a physical `client_secrets.json` file - for instance in managed or ephemeral environments. 

Could we add support for something like `credentials_json` as a JSON string of the contents of `client_secrets.json`? 

Relevant code snippets:

https://github.com/z3z1ma/target-bigquery/blob/2b771a26ae04ed34e7411b2bb3aa84c80ee9b141/target_bigquery/target.py#L318-L322

https://github.com/z3z1ma/target-bigquery/blob/2b771a26ae04ed34e7411b2bb3aa84c80ee9b141/target_bigquery/core.py#L213-L222

https://github.com/z3z1ma/target-bigquery/blob/2b771a26ae04ed34e7411b2bb3aa84c80ee9b141/target_bigquery/core.py#L578-L584

**Comment by daigotanaka** [comment]
Solved by #27 (thx @cjohnhanson!)
