### ISSUE TITLE
Update latest release version

### ISSUE THREAD

**Issue by Ella6882** [anelendata/tap-bigquery#28]
The releases only list up to 0.3.6 https://github.com/anelendata/tap-bigquery/releases, but the latest commit (https://github.com/anelendata/tap-bigquery/commit/acaf9f2221e89ed7e661ce60fd857d2eb6dbf85e) suggests to be at 0.3.7 to support env. Can we have the latest release be at 0.3.7?

**Comment by daigotanaka** [comment]
@Ella6882 Oops, my bad. Thx for reporting. I just created the tag.
